apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/pietervincken/renovate-tekton-argo-talk.git//k8s/monitoring?ref=main

patches:
  - target:
      kind: ServiceAccount
      name: thanos-store
    path: patches/thanos-sa-arn.yaml

  - target:
      kind: ServiceAccount
      name: prometheus-k8s
    path: patches/thanos-sa-arn.yaml

  - target:
      kind: PodDisruptionBudget
      name: prometheus-k8s
    path: patches/prometheus-k8s.yaml

secretGenerator:
  - name: thanos-objectstorage
    namespace: monitoring
    files:
      - "configs/thanos.yaml"
    options:
      disableNameSuffixHash: true
