apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render

patches:
  - target:
      kind: Deployment
      name: autoscaler-aws-cluster-autoscaler
    path: patches/deployment-clusterid.yaml

  - path: patches/sa-arn.yaml
    target:
      kind: ServiceAccount
      name: autoscaler-aws-cluster-autoscaler
