apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render

patches:
  - target:
      kind: Deployment
      name: cluster-autoscaler
    path: patches/deployment-clusterid.yaml
