apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render/
  - resources/ns.yaml
  - resources/secretstore.yaml
  - resources/serviceaccount.yaml
  # - resources/test-secret.yaml # only for testing.

namespace: external-secrets

patches:
  - target:
      kind: ServiceAccount
      name: renovate-talk-secret-store
    path: patches/sa-arn.yaml
