apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/autoscaler-argoapp.yaml
  - resources/aws-ebs-csi-driver.yaml
  - resources/certmanager-argoapp.yaml
  - resources/external-dns-argoapp.yaml
  - resources/external-secrets-operator-argoapp.yaml
  - resources/renovate-argoapp.yaml
  - resources/tekline-argoapp.yaml
  - resources/tekton-argoapp.yaml
  - resources/traefik-argoapp.yaml
  - https://github.com/pietervincken/renovate-talk-java-demo-app-deploy.git//argocd?ref=main

namespace: argocd

patches:
  - target:
      name: demo-java-app
      group: argoproj.io
      kind: Application
    path: patches/demo-app-images-registry.yaml
