apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/autoscaler-argoapp.yaml # TODO investigate add-on
  - resources/certmanager-argoapp.yaml
  - resources/external-dns-argoapp.yaml
  - resources/external-secrets-operator-argoapp.yaml
  # - resources/grafana-operator-argoapp.yaml
  # - resources/dashboarding-argoapp.yaml
  # - resources/prometheus-operator-argoapp.yaml
  # - resources/monitoring-argoapp.yaml

namespace: argocd
