apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/pietervincken/renovate-tekton-argo-talk.git//k8s/certmanager?ref=main

patches:
  - target:
      kind: ClusterIssuer
    path: patches/solver.yaml

  - path: patches/sa-arn.yaml
    target:
      kind: ServiceAccount
      name: cert-manager
