apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../renovate-tekton-argo-talk/k8s/certmanager/

patches:
  - target:
      kind: ClusterIssuer
    path: patches/solver.yaml

  - path: patches/sa-arn.yaml
    target:
      kind: ServiceAccount
      name: cert-manager
