AWSTemplateFormatVersion: "2010-09-09"
Description: Terraform backend creation for k8sonaws
Resources:
  k8sonawsbucket:
    Type: "AWS::S3::Bucket"
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "owner"
          Value: "pieter.vincken@ordina.be"
        - Key: "project"
          Value: "k8sonaws"
  k8sonawslock:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
      Tags:
        - Key: "owner"
          Value: "pieter.vincken@ordina.be"
        - Key: "project"
          Value: "k8sonaws"
Outputs:
  bucketname:
    Description: Name of the state bucket
    Value: !Ref k8sonawsbucket

  locktable:
    Description: Dynamo tablename for the lock
    Value: !Ref k8sonawslock
