apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: renovate-talk-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: renovate-talk-secret-store
            namespace: external-secrets
