---
# Source: aws-ebs-csi-driver/templates/tests/helm-tester.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ebs-csi-driver-test
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  containers:
    - name: kubetest2
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220624-1a63fdd9f2-master
      command: ["/bin/sh", "-c"]
      args:
        - "cp /etc/config/storageclass.yaml /workspace/storageclass.yaml\ngo install sigs.k8s.io/kubetest2/...@latest\nkubectl config set-cluster cluster --server=https://kubernetes.default --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt\nkubectl config set-context kubetest2 --cluster=cluster\nkubectl config set-credentials sa --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\nkubectl config set-context kubetest2 --user=sa && kubectl config use-context kubetest2\nkubectl get crd volumesnapshots.snapshot.storage.k8s.io\nif [ $? -eq 0 ]; then \n  SNAPSHOTS=\"|snapshot fields\"\nfi\nexport FOCUS_REGEX=\"\\bebs.csi.aws.com\\b.+(validate content|resize volume|offline PVC|AllowedTopologies|store data$SNAPSHOTS)\"\nkubetest2 noop --run-id='e2e-kubernetes' --test=ginkgo -- --test-package-version=$(curl -L https://dl.k8s.io/release/stable-1.25.txt) --skip-regex='\\[Disruptive\\]|\\[Serial\\]' --focus-regex=\"$FOCUS_REGEX\" --parallel=25 --test-args='-storage.testdriver=/etc/config/manifests.yaml'\n"
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  serviceAccountName: ebs-csi-driver-test
  volumes:
    - name: config-vol
      configMap:
        name: ebs-csi-driver-test
  restartPolicy: Never
