---
# Source: aws-ebs-csi-driver/templates/tests/helm-tester.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-csi-driver-test
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups: [""]
    resources:
      - events
      - nodes
      - pods
      - replicationcontrollers
      - serviceaccounts
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["list"]
  - apiGroups: [""]
    resources:
      - services
      - nodes
      - nodes/proxy
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/log
    verbs: ["get"]
  - apiGroups: [""]
    resources:
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/exec
    verbs: ["create"]
  - apiGroups: [""]
    resources:
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - pods
    verbs: ["delete"]
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs: ["update"]
  - apiGroups: [""]
    resources:
      - pods/ephemeralcontainers
    verbs: ["patch"]
  - apiGroups: [""]
    resources:
      - serviceaccounts
      - configmaps
    verbs: ["watch"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - daemonsets
    verbs: ["list"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["create"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - csinodes
    verbs: ["get"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
      - volumesnapshotclasses
      - volumesnapshotcontents
    verbs: ["create"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
      - volumesnapshotclasses
      - volumesnapshotcontents
    verbs: ["get"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshotcontents
    verbs: ["update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
      - volumesnapshotclasses
      - volumesnapshotcontents
    verbs: ["delete"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - clusterroles
    verbs: ["list"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
    verbs: ["list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
    verbs: ["create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["get"]
