---
# Source: aws-ebs-csi-driver/templates/serviceaccount-csi-controller.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/instance: aws-ebs-csi-driver
    helm.sh/chart: aws-ebs-csi-driver-2.22.0
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
