apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/render
- resources/ns.yaml
images:
- name: k8s.gcr.io/external-dns/external-dns
  newTag: v0.13.1

patches:
- path: patches/deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1
- path: patches/sa-arn.yaml
  target:
    kind: ServiceAccount
    name: external-dns

namespace: external-dns
