apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/pietervincken/renovate-talk-java-demo-app-deploy.git//kustomize

images:
  - name: renovatetalkacr.azurecr.io/renovate-talk-java-demo-app
    newName: pietervincken/renovate-talk-java-demo-app
    newTag: base
