apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/render

patches:
  - target:
      kind: ServiceAccount
      name: ebs-csi-controller-sa
    path: patches/sa-arn.yaml
